//
// Copyright (C) Chris Zankel. All rights reserved.
// This code is subject to U.S. and other copyright laws and
// intellectual property protections.
//
// The contents of this file are confidential and proprietary to Chris Zankel.
//

#ifndef GRID_MODEL_LLAMA_H
#define GRID_MODEL_LLAMA_H

#include <grid/tensor/tensor.h>

#include <iostream>

namespace grid {

const size_t kMaxTensorRank = 3;
const size_t kMaxTensorShards = 1;

template <template <typename, size_t, typename...> typename, typename> class LLaMAModelT;
class LLaMAFile;

/// LLaMAModel is an interface for providing a LLaMA base class without any templated paramters.
class LLaMAModel
{
 public:

  // Query Size = Embedding Size / Number of heads
  // Samples
  // Sequence Length
  // Number of Layers / n_layers
  //   same as? num_hidden_layers_
  // Number of Heads / n_heads / num_attention_heads_
  // Embedding Size or Model Size, carried throughout the transformer
  // Query Size equal to Key and Value size: size of the weights for each layer
  // Number of KV Head / n_kv_heads
  // Hidden Dim ??
  // vocab_size_
  // Input: seq_len x embedding_size
  // vocab: all encoded symbols
  // token or token id: index in the vocab table and embeddings
  // embeddings: encodes information and "closeliness" of information.
  // positional encoding and rotary positional embeddings (RoPE)
  //   The original transformer combines the input embeddings with positional
  //   information of the current input token that feeds into the encoder.
  //   LLaMA uses a ... 

  // each token selects an entry in the embedded table {n-vocab x embedding size}
  //
// FIXME: remove _?
  struct Parameters
  {
    size_t vocab_size_;   // size of the vocabulary table
    size_t embed_size_;   // same as model size or num_heads * query_size
    size_t hidden_dim_;   // hidden dimension
    size_t num_layers_;   // number of encoder/decoder layers
    size_t num_heads_;    // number of heads (multi-head attention)
    size_t num_kv_heads_; // number of key-value heads (typically same as num_heads_)
    size_t max_seq_len_;  // max sequence length
  };

  static constexpr uint32_t kBOS = 1;
  static constexpr uint32_t kEOS = 2;

 public:
  virtual ~LLaMAModel() = default;

  /// FIXME
  virtual void Generate(const std::string&, int steps) = 0;

  /// Load creates a new model and loads the specified file or memory-maps the file.
  template <template <typename, size_t, typename...> typename Tensor>
  static LLaMAModel* Load(const LLaMAFile&, bool mmap = true);

  /// Create creates a new model in memory.
  template <template <typename, size_t, typename...> typename Tensor, typename T>
  static LLaMAModel* Create(Parameters&);

  /// Create creates a new model for a memory mapped file.
  template <template <typename, size_t, typename...> typename Tensor, typename T>
  static LLaMAModel* Create(LLaMAFile&, Parameters&);
};


/// LLaMAFile is an interface for managing LLaMA files.
class LLaMAFile
{
 public:
  virtual ~LLaMAFile() = default;

  /// DataType returns the dominant data type of the file.
  virtual const std::type_info& DataType() const = 0;

  /// GetParameters returns a reference to the model paramters.
  virtual LLaMAModel::Parameters GetParameters() const = 0;

  /// PrintModelParameters prints the model informatio and parameter
  void PrintModelInfo(std::ostream&) const;
};


/// KarpathyFile are snapshots created by the Karpathy LLaMA2 implementation.
/// https://github.com/karpathy/llama2.c
class KarpathyFile : public LLaMAFile
{
  // Parameters embedded in the file (naming follows the source file)
  struct FileParameters
  {
    int dim;          // transformer dimension
    int hidden_dim;   // number of ffn dimensions
    int n_layers;     // number of layers
    int n_heads;      // number of query heads
    int n_kv_heads;   // number of key/value heads (can be < query heads because of multiquery)
    int vocab_size;   // vocabulary size, usually 256 (byte-level)
    int max_seq_len;  // max sequence length
  };

 public:
  /// Constructor
  ///
  /// @param path  Path for the model
  /// @param tokenizer_path  Path for the tokenizer model
  /// @throws system_error if any of the files does not exist.
  KarpathyFile(const std::string& path, const std::string& tokenizer_path = "tokenizer.bin");
  virtual ~KarpathyFile() = default;

  // LLaMAFile::
  virtual const std::type_info& DataType() const;
  virtual LLaMAModel::Parameters GetParameters() const;

  // FIXME: shouldn't output be last in arg list?
  /// Load loads the model data (memory-mapped).
  template <template <typename, size_t, typename...> typename Tensor, typename T>
  void Load(LLaMAModelT<Tensor, T>&, const LLaMAFile&) const;

 private:
  std::string     tokenizer_path_;
  std::string     path_;
  size_t          file_size_;
  FileParameters  parameters_;
};

#if 0
/// GgmlFile handles file formats generated by the Ggml project:
/// ...
class KarpathyFile : public LLaMAFile
{

};
#endif

} // end namespace grid

#endif // GRID_MODEL_LLAMA_H
